### ISSUE TITLE
Compatibility issue with Hof Bergmann animals (geese & rabbits)

### ISSUE THREAD

**Issue by Nozem1982** [Chissel/FS25_EnhancedAnimalSystem#2]
Hello!

First of all, I just want to say that your mod is absolutely amazing – great work! 🙌
I’ve only noticed a small issue when I add the mod to the Hof Bergmann map: the animals that come with this map (like geese and rabbits) disappear as soon as your mod is active.

Would it be possible to add these animals to your mod, or make it compatible with Hof Bergmann so they remain available? That would be fantastic!

Thanks a lot for your time and effort, and again, big compliments on your work.

Best regards,

**Comment by Chissel** [comment]
I will have a look on it. Can you send me your log and maybe the animal.xml from the map?

**Comment by Nozem1982** [comment]
Sure, thank you for looking into it!
I’ll send you my log.txt file and the animals.xml from the Hof Bergmann map so you can check what’s happening.

Thanks again for your help!

[log.txt](https://github.com/user-attachments/files/22501013/log.txt)

[animals.xml](https://github.com/user-attachments/files/22501015/animals.xml)

**Comment by Chissel** [comment]
The issue has been resolved. Will be released with the next update.

**Comment by Nozem1982** [comment]
Hello!Thanks a lot for the quick fix – really appreciate it! 🙏 I fully understand that a mod like this is always a work in progress, and I think you’re doing an amazing job.I also really enjoyed your FS22 version, especially the addition of male animals – that was such a great feature! Do you maybe plan to include this again in your FS25 version?Thanks again for all your work, I’m really looking forward to what’s coming next!Best regards,Verstuurd vanaf mijn iPhoneOp 23 sep 2025 om 23:12 heeft Chissel ***@***.***> het volgende geschreven:﻿Chissel left a comment (Chissel/FS25_EnhancedAnimalSystem#2)
The issue has been resolved. Will be released with the next update.

**Comment by Nozem1982** [comment]
Hello!

First of all, thank you very much for the new update – great work once again! 🙌 It’s really nice to see how the mod keeps improving step by step.

I noticed that on Hof Bergmann, most things now work fine, but the geese still don’t seem to function properly. Everything else looks really good though!

And if there’s ever a chance to collaborate again with Farmer Andy, I think it would make the experience on Hof Bergmann even more complete.

Thanks again for all the time and effort you’re putting into this mod – it’s very much appreciated!

Best regards,
